name: CI
on: push
jobs:
  test-library:
    name: Deno test
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: canary
      - name: Run tests
        run: deno test --allow-env

      - name: Get tag version
        if: startsWith(github.ref, 'refs/tags/')
        id: get_tag_version
        run: echo ::set-output name=TAG_VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: npm build
        run: deno task build:npm ${{steps.get_tag_version.outputs.TAG_VERSION}}

  jsr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Install deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: canary
      - name: Publish to JSR on tag
        run: deno run -A jsr:@david/publish-on-tag@0.1.3